// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWRttl1K8aYU34KnKuuh3YkaEm4lsHrs',
    appId: '1:584172101781:web:1f1aec91f5cdd7b0b23b9c',
    messagingSenderId: '584172101781',
    projectId: 'chat-app-9a36e',
    authDomain: 'chat-app-9a36e.firebaseapp.com',
    storageBucket: 'chat-app-9a36e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqHR6gwwhO1IS2Jdr_U5J0DgjDpwN4mE',
    appId: '1:584172101781:android:855916ac5cd5b45bb23b9c',
    messagingSenderId: '584172101781',
    projectId: 'chat-app-9a36e',
    storageBucket: 'chat-app-9a36e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1YpZojtblhntwYnIJ83OEEBRTrr6pGFo',
    appId: '1:584172101781:ios:befa13a6b1a4c17ab23b9c',
    messagingSenderId: '584172101781',
    projectId: 'chat-app-9a36e',
    storageBucket: 'chat-app-9a36e.appspot.com',
    iosClientId: '584172101781-u7pdqoug1fojk1ueu16eu1489ulhjgf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1YpZojtblhntwYnIJ83OEEBRTrr6pGFo',
    appId: '1:584172101781:ios:9ff591c5bb1709beb23b9c',
    messagingSenderId: '584172101781',
    projectId: 'chat-app-9a36e',
    storageBucket: 'chat-app-9a36e.appspot.com',
    iosClientId: '584172101781-8rgmgdjpsr1rsnanlv9mmnv1gvqbddh9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
